#ifndef APP_BUTTONS_ACTIONS_H
#define APP_BUTTONS_ACTIONS_H

typedef enum {
    BUTTON_TOGGLE_ACTION,
    BUTTON_MOMENTRAY_PRESSED_ACTION,
    BUTTON_MOMENTARY_RELEASED_ACTION,
    BUTTON_SINGLE_CLICK_ACTION,
    BUTTON_DOUBLE_CLICK_ACTION,
    BUTTON_TRIPLE_CLICK_ACTION,
    BUTTON_LONG_PRESSED_ACTION,
    BUTTON_LONG_RELEASED_ACTION,
    BUTTON_NONE_ACTION,
} teButtonAction;

#endif /* APP_BUTTONS_ACTIONS_H */
